[project]
name = "monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask",
    "numpy>=1.19.0,<2.0.0",
    "opencv-python>=4.5.0",
]

[project.scripts]
smart-pet-monitor = "monitor.main:main"
